/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebafigurasinter;

/**
 *
 * @author Usuario
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtRadioCir = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtLadoCuad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtBaseRect = new javax.swing.JTextField();
        TxtAlturaRect = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtBaseTriang = new javax.swing.JTextField();
        TxtAlturaTriang = new javax.swing.JTextField();
        BtnAreaCir = new javax.swing.JButton();
        BtnPerCir = new javax.swing.JButton();
        BtnAreaCuad = new javax.swing.JButton();
        BtnPerCuad = new javax.swing.JButton();
        BtnAreaRect = new javax.swing.JButton();
        BtnPerRect = new javax.swing.JButton();
        BtnAreaTriang = new javax.swing.JButton();
        BtnPerTriang = new javax.swing.JButton();
        BtnBorrarCir = new javax.swing.JButton();
        BtnBorrarCuad = new javax.swing.JButton();
        BtnBorrarRect = new javax.swing.JButton();
        BtnBorrarTriang = new javax.swing.JButton();
        BtnBorrarTodo = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        OutAreaCir = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        OutPerCir = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        OutAreaCuad = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        OutPerCuad = new javax.swing.JTextField();
        BtnHipo = new javax.swing.JButton();
        BtnTipoTriang = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        OutAreaRect = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        OutPerRect = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        OutAreaTriang = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        OutPerTriang = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        OutHipo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        OutTipoTriang = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Círculo");

        jLabel2.setText("Cuadrado");

        jLabel3.setText("Rectángulo");

        jLabel4.setText("Triángulo Rectángulo");

        jLabel5.setText("Radio");

        TxtRadioCir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRadioCirActionPerformed(evt);
            }
        });

        jLabel6.setText("Lado");

        jLabel7.setText("Base");

        jLabel8.setText("Altura");

        jLabel9.setText("Base");

        jLabel10.setText("Altura");

        BtnAreaCir.setText("Calcular Área Círculo");
        BtnAreaCir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAreaCirActionPerformed(evt);
            }
        });

        BtnPerCir.setText("Calcular Perímetro Círculo");
        BtnPerCir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPerCirActionPerformed(evt);
            }
        });

        BtnAreaCuad.setText("Calcular Área Cuadrado");
        BtnAreaCuad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAreaCuadActionPerformed(evt);
            }
        });

        BtnPerCuad.setText("Calcular Perímetro Cuadrado");
        BtnPerCuad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPerCuadActionPerformed(evt);
            }
        });

        BtnAreaRect.setText("Calcular Área Rectángulo");
        BtnAreaRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAreaRectActionPerformed(evt);
            }
        });

        BtnPerRect.setText("Calcular Perímetro Rectángulo");
        BtnPerRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPerRectActionPerformed(evt);
            }
        });

        BtnAreaTriang.setText("Calcular Área Triángulo");
        BtnAreaTriang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAreaTriangActionPerformed(evt);
            }
        });

        BtnPerTriang.setText("Calcular Perímetro Triángulo");
        BtnPerTriang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPerTriangActionPerformed(evt);
            }
        });

        BtnBorrarCir.setText("Borrar");
        BtnBorrarCir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarCirActionPerformed(evt);
            }
        });

        BtnBorrarCuad.setText("Borrar");
        BtnBorrarCuad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarCuadActionPerformed(evt);
            }
        });

        BtnBorrarRect.setText("Borrar");
        BtnBorrarRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarRectActionPerformed(evt);
            }
        });

        BtnBorrarTriang.setText("Borrar");
        BtnBorrarTriang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarTriangActionPerformed(evt);
            }
        });

        BtnBorrarTodo.setText("Borrar Todo");
        BtnBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarTodoActionPerformed(evt);
            }
        });

        jLabel11.setText("Área Círculo");

        jLabel12.setText("Perímetro Círculo");

        jLabel13.setText("Área Cuadrado");

        jLabel14.setText("Perímetro Cuadrado");

        BtnHipo.setText("Calcular Hipotenusa");
        BtnHipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHipoActionPerformed(evt);
            }
        });

        BtnTipoTriang.setText("Determinar Tipo Triángulo");
        BtnTipoTriang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTipoTriangActionPerformed(evt);
            }
        });

        jLabel16.setText("Área Rectángulo");

        jLabel17.setText("Perímetro Rectángulo");

        jLabel18.setText("Área triángulo");

        jLabel19.setText("Perímetro Triángulo");

        jLabel20.setText("Hipotenusa");

        jLabel21.setText("Tipo Triángulo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(TxtRadioCir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtLadoCuad, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1)
                        .addGap(120, 120, 120)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtBaseRect, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtAlturaRect, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(TxtAlturaTriang, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(TxtBaseTriang, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(OutAreaCir, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnPerCir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnAreaCir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnBorrarCir, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OutPerCir, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(BtnPerCuad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtnAreaCuad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(BtnBorrarCuad)
                                    .addComponent(jLabel13))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(BtnPerRect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BtnAreaRect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(BtnBorrarRect)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(OutAreaRect)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel15))
                                            .addComponent(jLabel17)
                                            .addComponent(OutPerRect, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)))))
                            .addComponent(jLabel14)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OutPerCuad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OutAreaCuad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OutHipo)
                            .addComponent(OutPerTriang)
                            .addComponent(BtnTipoTriang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnHipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnAreaTriang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnPerTriang, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(OutAreaTriang)
                            .addComponent(OutTipoTriang)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnBorrarTriang)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(65, 65, 65))))
            .addGroup(layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(BtnBorrarTodo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtRadioCir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(TxtLadoCuad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(TxtBaseRect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(TxtBaseTriang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TxtAlturaRect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(TxtAlturaTriang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAreaCir)
                    .addComponent(BtnAreaCuad)
                    .addComponent(BtnAreaRect)
                    .addComponent(BtnAreaTriang))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPerCir)
                    .addComponent(BtnPerCuad)
                    .addComponent(BtnPerRect)
                    .addComponent(BtnPerTriang))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBorrarCir)
                    .addComponent(BtnBorrarCuad)
                    .addComponent(BtnBorrarRect)
                    .addComponent(BtnHipo))
                .addGap(18, 18, 18)
                .addComponent(BtnTipoTriang)
                .addGap(24, 24, 24)
                .addComponent(BtnBorrarTriang)
                .addGap(27, 27, 27)
                .addComponent(BtnBorrarTodo)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OutAreaCir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OutAreaCuad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OutAreaRect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OutAreaTriang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OutPerCir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OutPerCuad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OutPerRect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OutPerTriang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OutHipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OutTipoTriang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtRadioCirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRadioCirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRadioCirActionPerformed

    private void BtnAreaCirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAreaCirActionPerformed
        double Radio=Double.parseDouble(TxtRadioCir.getText());
        Circulo circulo= new Circulo(Radio);
        double Area=circulo.calcularArea();
        OutAreaCir.setText(String.valueOf(Area));
        
    }//GEN-LAST:event_BtnAreaCirActionPerformed

    private void BtnAreaCuadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAreaCuadActionPerformed
        double Lado=Double.parseDouble(TxtLadoCuad.getText());
        Cuadrado cuadrado= new Cuadrado(Lado);
        double Area=cuadrado.calcularArea();
        OutAreaCuad.setText(String.valueOf(Area));
    }//GEN-LAST:event_BtnAreaCuadActionPerformed

    private void BtnAreaRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAreaRectActionPerformed
        double Base=Double.parseDouble(TxtBaseRect.getText());
        double Altura=Double.parseDouble(TxtAlturaRect.getText());
        Rectangulo rectangulo=new Rectangulo(Base,Altura);
        double Area=rectangulo.calcularArea();
        OutAreaRect.setText(String.valueOf(Area));
    }//GEN-LAST:event_BtnAreaRectActionPerformed

    private void BtnAreaTriangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAreaTriangActionPerformed
        double Base=Double.parseDouble(TxtBaseTriang.getText());
        double Altura=Double.parseDouble(TxtAlturaTriang.getText());
        TrianguloRectangulo triangulo=new TrianguloRectangulo(Base,Altura);
        double Area=triangulo.calcularArea();
        OutAreaTriang.setText(String.valueOf(Area));
    }//GEN-LAST:event_BtnAreaTriangActionPerformed

    private void BtnPerCirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPerCirActionPerformed
        double Radio=Double.parseDouble(TxtRadioCir.getText());
        Circulo circulo= new Circulo(Radio);
        double Peri=circulo.calcularPerimetro();
        OutPerCir.setText(String.valueOf(Peri));
    }//GEN-LAST:event_BtnPerCirActionPerformed

    private void BtnBorrarCirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarCirActionPerformed
        TxtRadioCir.setText("");
        OutPerCir.setText("");
        OutAreaCir.setText("");
    }//GEN-LAST:event_BtnBorrarCirActionPerformed

    private void BtnPerCuadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPerCuadActionPerformed
        double Lado=Double.parseDouble(TxtLadoCuad.getText());
        Cuadrado cuadrado= new Cuadrado(Lado);
        double Peri=cuadrado.calcularPerimetro();
        OutPerCuad.setText(String.valueOf(Peri));
    }//GEN-LAST:event_BtnPerCuadActionPerformed

    private void BtnBorrarCuadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarCuadActionPerformed
       OutPerCuad.setText("");
       OutAreaCuad.setText("");
       TxtLadoCuad.setText("");
    }//GEN-LAST:event_BtnBorrarCuadActionPerformed

    private void BtnPerRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPerRectActionPerformed
        double Base=Double.parseDouble(TxtBaseRect.getText());
        double Altura=Double.parseDouble(TxtAlturaRect.getText());
        Rectangulo rectangulo=new Rectangulo(Base,Altura);
        double Peri=rectangulo.calcularPerimetro();
        OutPerRect.setText(String.valueOf(Peri));
    }//GEN-LAST:event_BtnPerRectActionPerformed

    private void BtnBorrarRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarRectActionPerformed
        OutPerRect.setText("");
        OutAreaRect.setText("");
        TxtBaseRect.setText("");
        TxtAlturaRect.setText("");
    }//GEN-LAST:event_BtnBorrarRectActionPerformed

    private void BtnPerTriangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPerTriangActionPerformed
        double Base=Double.parseDouble(TxtBaseTriang.getText());
        double Altura=Double.parseDouble(TxtAlturaTriang.getText());
        TrianguloRectangulo triangulo=new TrianguloRectangulo(Base,Altura);
        double Peri=triangulo.calcularPerimetro();
        OutPerTriang.setText(String.valueOf(Peri));
    }//GEN-LAST:event_BtnPerTriangActionPerformed

    private void BtnHipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHipoActionPerformed
        double Base=Double.parseDouble(TxtBaseTriang.getText());
        double Altura=Double.parseDouble(TxtAlturaTriang.getText());
        TrianguloRectangulo triangulo=new TrianguloRectangulo(Base,Altura);
        double Hipo=triangulo.calcularHipotenusa();
        OutHipo.setText(String.valueOf(Hipo));
    }//GEN-LAST:event_BtnHipoActionPerformed

    private void BtnTipoTriangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTipoTriangActionPerformed
        double Base=Double.parseDouble(TxtBaseTriang.getText());
        double Altura=Double.parseDouble(TxtAlturaTriang.getText());
        TrianguloRectangulo triangulo=new TrianguloRectangulo(Base,Altura);
        String Tipo=triangulo.determinarTipoTriangulo();
        OutTipoTriang.setText(Tipo);
    }//GEN-LAST:event_BtnTipoTriangActionPerformed

    private void BtnBorrarTriangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarTriangActionPerformed
        OutTipoTriang.setText("");
        OutHipo.setText("");
        OutPerTriang.setText("");
        OutAreaTriang.setText("");
        TxtBaseTriang.setText("");
        TxtAlturaTriang.setText("");
    }//GEN-LAST:event_BtnBorrarTriangActionPerformed

    private void BtnBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarTodoActionPerformed
        OutTipoTriang.setText("");
        OutHipo.setText("");
        OutPerTriang.setText("");
        OutAreaTriang.setText("");
        TxtBaseTriang.setText("");
        TxtAlturaTriang.setText("");
        OutPerRect.setText("");
        OutAreaRect.setText("");
        TxtBaseRect.setText("");
        TxtAlturaRect.setText("");
        OutPerCuad.setText("");
        OutAreaCuad.setText("");
        TxtLadoCuad.setText("");
        TxtRadioCir.setText("");
        OutPerCir.setText("");
        OutAreaCir.setText("");
    }//GEN-LAST:event_BtnBorrarTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAreaCir;
    private javax.swing.JButton BtnAreaCuad;
    private javax.swing.JButton BtnAreaRect;
    private javax.swing.JButton BtnAreaTriang;
    private javax.swing.JButton BtnBorrarCir;
    private javax.swing.JButton BtnBorrarCuad;
    private javax.swing.JButton BtnBorrarRect;
    private javax.swing.JButton BtnBorrarTodo;
    private javax.swing.JButton BtnBorrarTriang;
    private javax.swing.JButton BtnHipo;
    private javax.swing.JButton BtnPerCir;
    private javax.swing.JButton BtnPerCuad;
    private javax.swing.JButton BtnPerRect;
    private javax.swing.JButton BtnPerTriang;
    private javax.swing.JButton BtnTipoTriang;
    private javax.swing.JTextField OutAreaCir;
    private javax.swing.JTextField OutAreaCuad;
    private javax.swing.JTextField OutAreaRect;
    private javax.swing.JTextField OutAreaTriang;
    private javax.swing.JTextField OutHipo;
    private javax.swing.JTextField OutPerCir;
    private javax.swing.JTextField OutPerCuad;
    private javax.swing.JTextField OutPerRect;
    private javax.swing.JTextField OutPerTriang;
    private javax.swing.JTextField OutTipoTriang;
    private javax.swing.JTextField TxtAlturaRect;
    private javax.swing.JTextField TxtAlturaTriang;
    private javax.swing.JTextField TxtBaseRect;
    private javax.swing.JTextField TxtBaseTriang;
    private javax.swing.JTextField TxtLadoCuad;
    private javax.swing.JTextField TxtRadioCir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
